# Generated by Django 4.2.1 on 2023-05-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary_app', '0002_binarytreenode_left_binarytreenode_right'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binarytreenode',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='binarytreenode',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
