# Generated by Django 4.2.1 on 2023-05-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary_app', '0003_alter_binarytreenode_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binarytreenode',
            name='parent_id',
            field=models.IntegerField(max_length=20),
        ),
    ]
