# Generated by Django 4.2.1 on 2023-05-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary_app', '0004_alter_binarytreenode_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binarytreenode',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
